import Head from "next/head";
import { Inter } from "next/font/google";
import { Typography } from "@mui/material";
import AppBar from "@mui/material/AppBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Typography variant="h1">
          なんでこんなにエラーがでてしまうのだろう
        </Typography>
        <Typography variant="h1">
          なんでこんなにエラーがでてしまうのだろう
        </Typography>
        <Typography variant="h1">
          なんでこんなにエラーがでてしまうのだろう
        </Typography>
        <Typography variant="h1">
          なんでこんなにエラーがでてしまうのだろう
        </Typography>
        <AppBar>aaa,aaa,aaa</AppBar>
      </main>
    </>
  );
}
